[toolchain]
anchor_version = "0.32.1"
package_manager = "yarn"

[features]
seeds = false
skip-lint = false

[programs.devnet]
list_contract = "D6J4e2nQDFupaitnirnp7HerHw5zdpGwNyRvJUrVu7ji"

[programs.mainnet]
list_contract = "D6J4e2nQDFupaitnirnp7HerHw5zdpGwNyRvJUrVu7ji"

[programs.localnet]
list_contract = "7QcpGHW5VfPe2U2SoSqQhQmtqVMD1FLBeGxLLT2DxWpj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://solana-mainnet.g.alchemy.com/v2/olUaug5e7HLKLIeYPBlUH"
wallet = "./deploy-wallet.json"

[scripts]
initialize = "yarn ts-node scripts/1_initialize.ts"
createTokenFrozen = "yarn ts-node scripts/2_create_frozen_mint_local.ts"

checkMint = "yarn ts-node scripts/checkMint.ts"
initializeExtaAccountMetaList = "yarn ts-node scripts/3_initializeExtaAccountMetaList.ts"
createMintWithMetadata = "yarn ts-node scripts/create_mint_with_metadata.ts"
createcreateFrozenFintLocalMintWithMetadata = "yarn ts-node scripts/create_frozen_mint_local.ts"
getMintAuthorityKey = "yarn ts-node scripts/getMintAuthorityKey.ts"
getPDA = "yarn ts-node scripts/getPDA.ts"
getTreasury = "yarn ts-node scripts/getTreasury.ts"
testSettleClick = "yarn ts-node scripts/test_settle_click.ts"
balance = "yarn ts-node check_deploy_balance.ts"

